version: '2'

services:
  solr:
    image: elasticsearch:5.5.2
    ports:
     - "9300:9300"
    volumes:
      - data:/usr/share/elasticsearch/data
    entrypoint:
      - docker-entrypoint.sh
      - d8
volumes:
  data:
