plugin.plugin_configuration.search_api_elasticsearch_connector.basic_auth:
  type: plugin.plugin_configuration.search_api_elasticsearch_connector.standard
  label: 'Search API Elasticsearch basic authentication connector settings'
  mapping:
    username:
      type: string
      label: 'Username for HTTP basic authentication'
    password:
      type: string
      label: 'Password for HTTP basic authentication'
